rules:
    no-ids: 0
    no-color-literals: 0
    no-color-keywords: 0
    nesting-depth:
        - 1
        -
          max-depth: 4
    placeholder-in-extend: 0
    property-sort-order:
        - 1
        -
          order: 'concentric'
    indentation:
        - 1
        -
          size: 4
